config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'playlists#index'

  resources :playlists, :tracks, :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = SpotifyCaller.get_album(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :get_spotify_token
  before_action :get_playlist_title, only: [:show]

  def index
    playlists_response = SpotifyCaller.get_featured_playlists(@token)
    @playlists = playlists_response['playlists']['items']
  end

  def show
    playlist_response = SpotifyCaller.get_individual_playlist(@token, params[:user_id], params[:id])
    @playlist = playlist_response['items']
  end

  private
    def get_spotify_token
      spot_auth_call = SpotifyCaller.spotify_authorize
      login_response = spot_auth_call.parsed_response
      @token = login_response['access_token']
    end

    def get_playlist_title
      @playlist_title = params[:playlist_title]
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = SpotifyCaller.get_individual_track(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spotify_caller.rb
module SpotifyCaller
  def self.client_id
    Rails.application.secrets.spotify_client_id
  end

  def self.client_secret
    Rails.application.secrets.spotify_client_secret
  end

  def self.encoded_client
    Base64.encode64(SpotifyCaller.client_id + ":" + SpotifyCaller.client_secret).delete("\n")
  end

  def self.spotify_authorize
    HTTParty.post("https://accounts.spotify.com/api/token",
      :query => { :grant_type => "client_credentials" },
      :headers => { "Authorization" => "Basic " + self.encoded_client }
    )
  end

  def self.get_featured_playlists(token)
    HTTParty.get("https://api.spotify.com/v1/browse/featured-playlists?country=US&limit=50",
      :headers => { "Authorization" => "Bearer " + token }
    )
  end

  def self.get_individual_playlist(token, user_id, playlist_id)
    HTTParty.get("https://api.spotify.com/v1/users/#{user_id}/playlists/#{playlist_id}/tracks",
      :headers => { "Authorization" => "Bearer " + token }
    )
  end

  def self.get_individual_track(track_id)
    HTTParty.get("https://api.spotify.com/v1/tracks/#{track_id}")
  end

  def self.get_album(album_id)
    HTTParty.get("https://api.spotify.com/v1/albums/#{album_id}")
  end
end

app/views/albums/show.html.erb
<div class="container-fluid">
    <h1><%= @album['name'] %></h1>

    <div class="row track-panel z-depth-1">
      <div class="track-photo col-md-2">
        <%= image_tag(@album['images'][0]['url']) %>
      </div>
      <div class="track-details col-md-3">
        <div class="row">
          Album Title: <%= @album['name'] %>
        </div>
        <div class="row">
          Artist: <%= @album['artists'][0]['name'] %>
        </div>
        <div class="row">
          Album Release Date: <%= @album['release_date'] %>
        </div>
      </div>
      <div class="track-analytics col-md-3">
        <div class="row">
          Popularity: <%= @album['popularity'] %>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listify</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.1.1/css/mdb.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.1.1/js/mdb.min.js"></script>

</head>
<body>
  <header>
    <h1 class="z-depth-1">Listify</h1>
  </header>

<%= yield %>

</body>
</html>

app/views/playlists/index.html.erb
<div class="container-fluid">
  <% @playlists.each do |playlist| %>
    <div class="card playlist-card col-md-1">
      <%= link_to image_tag(playlist['images'][0]['url'], class: "img-fluid"),
       playlist_path(playlist['id'], params: {user_id: playlist['owner']['id'], playlist_title: playlist['name']} )
      %>
      <div class="card-block">
        <%= playlist['name'] %>
        <div class="row">
          # Tracks: <%= playlist['tracks']['total'] %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/playlists/show.html.erb
<div class="container-fluid">
  <h1><%= @playlist_title %></h1>

  <% @playlist.each do |track_object| %>
    <div class="row track-panel z-depth-1">
      <div class="track-photo col-md-2">
        <%= link_to image_tag(track_object['track']['album']['images'][0]['url']),
        track_path(track_object['track']['id']) %>
      </div>
      <div class="track-details col-md-3">
        <div class="row">
          Title: <%= track_object['track']['name'] %>
        </div>
        <div class="row">
          Artist: <%= track_object['track']['artists'][0]['name'] %>
        </div>
        <div class="row">
          From the Album: <%= track_object['track']['album']['name'] %>
        </div>
        <div class="row">
          Added To This Playlist: <%= time_ago_in_words(track_object['added_at']) + " ago" %>
        </div>
        <div class="row">
          Album Release Date:
        </div>
      </div>
      <div class="track-analytics col-md-3">
        <div class="row">
          Popularity: <%= track_object['track']['popularity'] %>
        </div>
        <div class="row">
          Other playlists containing this song:
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tracks/show.html.erb
<div class="container-fluid">
  <h1><%= @track['name'] %></h1>

  <ul>
    <div class="row track-panel z-depth-1">
      <div class="track-photo col-md-2">
        <%= link_to image_tag(@track['album']['images'][0]['url']), album_path(@track['album']['id']) %>
      </div>
      <div class="track-details col-md-4">
        <div class="row">
          Title: <%= @track['name'] %>
        </div>
        <div class="row">
          Artist: <%= @track['artists'][0]['name'] %>
        </div>
        <div class="row">
          From the Album: <%= @track['album']['name'] %>
        </div>
      </div>
      <div class="track-analytics col-md-4">
        <div class="row">
          Popularity: <%= @track['popularity'] %>
        </div>
        <div class="row">
          Number of playlists containing this song
        </div>
      </div>
    </div>
  </ul>
</div>